name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v3
    
    - name: 🔧 Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.WHM_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.WHM_HOST }} >> ~/.ssh/known_hosts
    
    - name: 📤 Deploy via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='news' \
          ./ root@${{ secrets.WHM_HOST }}:/home/githubdemo/public_html/
        
    - name: ✅ Deployment Complete
      run: echo "Successfully deployed to githubdemo.com"