name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v3
    
    - name: 🔧 Setup SSH using webfactory action
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.WHM_SSH_KEY }}
    
    - name: 🔍 Add server to known hosts
      run: |
        ssh-keyscan -H 83.223.113.88 >> ~/.ssh/known_hosts
    
    - name: 📤 Deploy via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='news' \
          ./ root@83.223.113.88:/home/githubdemo/public_html/
        
    - name: ✅ Deployment Complete
      run: echo "Successfully deployed to githubdemo.com"