name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v3
    
    - name: 📤 Deploy to cPanel via SSH
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.WHM_HOST }}
        username: ${{ secrets.WHM_USERNAME }}
        key: ${{ secrets.WHM_SSH_KEY }}
        source: "./*"
        target: "/home/githubdemo/public_html"
        rm: true
        exclude: ".git,.github,news"
        
    - name: ✅ Deployment Complete
      run: echo "Successfully deployed to githubdemo.com"